services:
  sparksplayer:
    build: .
    container_name: sparksplayer
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - "/mnt/d/Instrumentals/Sparks/multitrack:/usr/src/app/client/multitrack"
